/* Shapes the Super Admin dashboard renders. They mirror the planned API resources:
   GET /api/v1/admin/dashboard/stats and GET /api/v1/admin/dashboard/charts?year= (PRD §11).
   Money is a plain number in `currency`; formatting happens in the UI. */

export type CompanyStatus = 'active' | 'inactive'

export interface DashboardStats {
  /** Sum of approved plan orders. */
  totalRevenue: number
  totalCompanies: number
  /** Companies registered this month vs last, as a fraction (0.55 = +55%). */
  companiesGrowth: number
  activePlans: number
  /** Month-over-month growth, as a fraction. */
  monthlyGrowth: number
  pendingRequests: number
}

export interface RecentCompany {
  id: number
  name: string
  email: string
  status: CompanyStatus
  /** ISO 8601 timestamp. */
  joinedAt: string
}

export interface TopPlan {
  id: number
  name: string
  /** Revenue generated by this plan, in `currency`. */
  revenue: number
  subscribers: number
}

export interface AdminDashboardSummary {
  currency: string
  stats: DashboardStats
  /** Newest first, at most 5. */
  recentCompanies: RecentCompany[]
  /** Highest revenue first, at most 3. */
  topPlans: TopPlan[]
  /** Years the charts can show, newest first. */
  chartYears: number[]
}

export interface AdminDashboardCharts {
  year: number
  currency: string
  /** 12 values, January → December. */
  companiesByMonth: number[]
  /** 12 values, January → December, in `currency`. */
  revenueByMonth: number[]
}
